///Hello Professor Jang, this is the chatbot intake flow for TrustMed AI
///This screen implements a 4-step guided intake:
///1) Free-text concern description (User Input)
///2) AI-assisted concern categorization (LLM Generated)
///3) Symptom severity ratings (LLM Symptom Generated)
///4) Risk assessment + suggested questions for a clinician (Coded Risk Scoring logic & LLM Generated Analysis Response)
///I have added comments for your guidance in explaining the code

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Fonts } from '@/constants/theme';
import Slider from '@react-native-community/slider';
import { useMemo, useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  TextInput,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';



///The interfaces below describe the data that gets sent to and received from
///the backend symptom-intake API. 

///The interface below is specifically the request format for
///POST /v1/intake/concern-analyze — this is what is sent when the user
///enters their symptoms through free text. Only "freeTextConcern" is required.

interface ConcernAnalyzeRequest {
  sessionId?: string;
  locale?: string;
  freeTextConcern: string;
  ageYears?: number;
  sexAtBirth?: 'female' | 'male' | 'intersex' | 'unknown';
  currentPregnancyStatus?:
    | 'pregnant'
    | 'possibly_pregnant'
    | 'not_pregnant'
    | 'unknown';
}

interface ConcernAnalyzeResponse {
  sessionId?: string;
  primaryCategory: string;
  candidateCategories: string[];
  clinicalSummary: string;
  psychosocialFactorsMentioned: boolean;
  durationText?: string;
  bodyLocations?: string[];
  safetyNotes: string[];
}

//This tells the app where my backend server is running.
//During development it's http://localhost:3000, but when deployed it becomes the live backend URL.
const API_BASE_URL = 'https://trustmedai.onrender.com';


///SymptomRating stores each symptom and the severity slider value.
///RiskAssessment stores the output of my local risk scoring and the text sections shown in Step 4.
/// These structures are front-end only (not generated by the backend or the LLM).
interface SymptomRating {
  symptom: string;
  severity: number; 
}

interface RiskAssessment {
  level: 'Low' | 'Moderate' | 'High';
  concernType: string;
  brief: string;
  redFlags: string[];
  analysis: string;
  recommendations: string[];
}

///Legacy prototype function:
///I used this early on to simulate classification before I had a backend.
///Currently not used, but kept here as a reference for how the project evolved.

const classifyConcern = (input: string): string[] => {
  const txt = input.toLowerCase();
  if (/chest|heart|pressure|tight/.test(txt)) {
    return ['Heart-related issue', 'Anxiety/Panic Attack', 'Respiratory Issue'];
  }
  if (/fever|cough|cold|throat/.test(txt)) {
    return ['Cold/Flu', 'COVID-19', 'Strep Throat', 'Allergies'];
  }
  if (/stomach|nausea|vomit|diarrhea/.test(txt)) {
    return ['Food Poisoning', 'Stomach Flu', 'IBS', 'Gastritis'];
  }
  if (/head|migraine/.test(txt)) {
    return ['Migraine', 'Tension Headache', 'Sinus Issue'];
  }
  return ['General Malaise', 'Viral Infection', 'Stress/Anxiety'];
};

///High level Concern category and a Subsidiary list of related symptoms that will appear on the slide symptoms step
///*A default "generic" list is used if the category is unknown*
///
///Static symptom lookup used in this prototype.
///In a future version this could be replaced with LLM-generated symptom lists.
const getSymptomsForConcern = (concern: string): string[] => {
  const symptomsMap: Record<string, string[]> = {
    'Heart-related issue': [
      'Chest pain',
      'Shortness of breath',
      'Dizziness',
      'Sweating',
      'Nausea',
      'Arm pain',
    ],
    'Anxiety/Panic Attack': [
      'Rapid heartbeat',
      'Shortness of breath',
      'Dizziness',
      'Sweating',
      'Trembling',
      'Chest tightness',
    ],
    'Respiratory Issue': [
      'Cough',
      'Wheezing',
      'Shortness of breath',
      'Chest tightness',
      'Fatigue',
    ],
    'Cold/Flu': [
      'Fever',
      'Cough',
      'Sore throat',
      'Runny nose',
      'Body aches',
      'Fatigue',
      'Headache',
    ],
    'COVID-19': [
      'Fever',
      'Dry cough',
      'Fatigue',
      'Loss of taste/smell',
      'Shortness of breath',
      'Body aches',
    ],
    'Strep Throat': [
      'Sore throat',
      'Fever',
      'Swollen lymph nodes',
      'Difficulty swallowing',
      'Red tonsils',
    ],
    'Food Poisoning': [
      'Nausea',
      'Vomiting',
      'Diarrhea',
      'Abdominal pain',
      'Fever',
      'Weakness',
    ],
    'Stomach Flu': [
      'Nausea',
      'Vomiting',
      'Diarrhea',
      'Abdominal cramps',
      'Fever',
      'Dehydration',
    ],
    Migraine: [
      'Severe headache',
      'Nausea',
      'Light sensitivity',
      'Sound sensitivity',
      'Visual disturbances',
    ],
    'Tension Headache': [
      'Dull headache',
      'Pressure around head',
      'Neck pain',
      'Shoulder tension',
    ],
  };

///This array is suppose to make sure it does not show duplicate symptoms
///Semi-Works on my end, doesn't show the exact same symptoms but there are occasions
///Where it is just labeled differently. Ex. "Chest Pain" and "Chest Discomfort"
  return Array.from(
    new Set(symptomsMap[concern] || ['Fatigue', 'Pain', 'Discomfort', 'Weakness'])
  );
};

///Simple risk scoring based on how many symptoms
///are rated Mild/Moderate/Severe. This is a heuristic used to
///illustrate logic in the prototype.

///This is not based on a medical model, it’s a heuristic approach I wrote to illustrate
///how structured symptom inputs could be turned into a basic risk level
///inside the prototype. The LLM later rewrites this into a more clinical
///reporrt in Step 4.
///
///In the full system, this logic could be replaced or enhanced with a
///real triage model if ever used on patients, but for the prototype it just demonstrates the workflow.
const analyzeRisk = (concern: string, ratings: SymptomRating[]): RiskAssessment => {
  const severeCount = ratings.filter((r) => r.severity === 3).length;
  const moderateCount = ratings.filter((r) => r.severity === 2).length;
  const totalScore = ratings.reduce((sum, r) => sum + r.severity, 0);

  let level: 'Low' | 'Moderate' | 'High' = 'Low';
  if (severeCount >= 2 || totalScore >= 12) {
    level = 'High';
  } else if (severeCount >= 1 || totalScore >= 6) {
    level = 'Moderate';
  }

///Simple red-flag safety messages based on concerns and severity for when tested on users
  const redFlags: string[] = [];
  if (concern === 'Heart-related issue' && severeCount > 0) {
    redFlags.push('Severe chest symptoms require immediate medical attention');
    redFlags.push('Call 911 if symptoms worsen or include arm/jaw pain');
  }
  if (
    concern === 'COVID-19' &&
    ratings.find((r) => r.symptom.includes('breath') && r.severity >= 2)
  ) {
    redFlags.push('Difficulty breathing requires immediate medical evaluation');
  }
  if (level === 'High') {
    redFlags.push('Multiple severe symptoms present - seek immediate care');
  }

  ////Build a readable summary of the rated symptoms for analysis and display.
  const symptomsText = ratings
    .filter((r) => r.severity > 0)
    .map(
      (r) => `${r.symptom} (${['None', 'Mild', 'Moderate', 'Severe'][r.severity]})`
    )
    .join(', ');
  ///RiskAssessment object consumed by Step 4 (summary + recommendations UI).
  return {
    level,
    concernType: concern,
    brief: `Patient reports ${concern.toLowerCase()} with ${ratings.length} assessed symptoms. Overall risk level: ${level}.`,
    redFlags,
    analysis: `Based on your reported symptoms (${symptomsText}), you are experiencing ${level.toLowerCase()}-level concern. The symptom pattern suggests ${concern.toLowerCase()}, which ${
      level === 'High'
        ? 'requires immediate medical attention'
        : level === 'Moderate'
        ? 'should be evaluated by a healthcare provider soon'
        : 'can likely be managed with self-care, but monitor for changes'
    }.`, 
    recommendations:
      level === 'High'
        ? [
            'Seek immediate medical attention',
            'Visit ER or urgent care',
            'Call 911 if symptoms worsen',
            'Do not drive yourself',
          ]
        : level === 'Moderate'
        ? [
            'Schedule appointment with doctor within 24-48 hours',
            'Monitor symptoms closely',
            'Rest and stay hydrated',
            'Seek immediate care if symptoms worsen',
          ]
        : [
            'Rest and monitor symptoms',
            'Stay hydrated',
            'Use over-the-counter medications if appropriate',
            'Contact doctor if symptoms persist beyond 3-5 days',
          ],
  };
};

///Stepper Steps
const TOTAL_STEPS = 4;
///Labels for slider severity levels.
const SEVERITY_LABELS = ['None', 'Mild', 'Moderate', 'Severe'];

///Main screen component for the TrustMed AI intake flow.
///Implements a 4-step guided symptom intake and assessment.
export default function ChatbotScreen() {
  const insets = useSafeAreaInsets();


  const [step, setStep] = useState(1);
  const [isLoading, setIsLoading] = useState(false);

  const [clinicalSummary, setClinicalSummary] = useState<string | null>(null);


  const [freeText, setFreeText] = useState('');
  const [concernSuggestions, setConcernSuggestions] = useState<string[]>([]);


  const [selectedConcern, setSelectedConcern] = useState<string>('');


  const [symptomRatings, setSymptomRatings] = useState<SymptomRating[]>([]);


  const [riskAssessment, setRiskAssessment] = useState<RiskAssessment | null>(
    null
  );
  const [doctorQuestions, setDoctorQuestions] = useState<string[]>([]);

///(Currently unused - leftover from earlier UI version) Legacy Prototype Code
  const symptomsList = useMemo(() => {
    if (!selectedConcern) return [];
    return getSymptomsForConcern(selectedConcern);
  }, [selectedConcern]);

  
  const handleAnalyzeText = async () => {
    if (!freeText.trim()) return;

    setIsLoading(true);

    const payload: ConcernAnalyzeRequest = {
      freeTextConcern: freeText.trim(),
      locale: 'en-US',
    };

    try {
      const res = await fetch(`${API_BASE_URL}/v1/intake/concern-analyze`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errorText = await res.text();
        console.error('API error status:', res.status, 'body:', errorText);
        return;
      }

      const data: ConcernAnalyzeResponse = await res.json();
      console.log('API response:', data);

      const suggestions = [
        data.primaryCategory,
        ...(data.candidateCategories || []),
      ].filter(Boolean);

      setConcernSuggestions(suggestions);
      setClinicalSummary(data.clinicalSummary || null);
      setStep(2);
    } catch (err) {
      console.error('Network or parsing error', err);
    } finally {
      setIsLoading(false);
    }
  };


  const handleSelectConcern = (concern: string) => {
    setSelectedConcern(concern);

    const symptoms = getSymptomsForConcern(concern);
    setSymptomRatings(symptoms.map((s) => ({ symptom: s, severity: 0 })));

    setStep(3);
  };

  
  const handleUpdateSeverity = (index: number, severity: number) => {
    const updated = [...symptomRatings];
    updated[index].severity = severity;
    setSymptomRatings(updated);
  };


  const handleGenerateAssessment = async () => {
    if (!selectedConcern || symptomRatings.length === 0) return;

    setIsLoading(true);

    const localAssessment = analyzeRisk(selectedConcern, symptomRatings);

    const symptomSummary =
      symptomRatings
        .filter((r) => r.severity > 0)
        .map((r) => `${r.symptom} (${SEVERITY_LABELS[r.severity]})`)
        .join(', ') || 'No significant symptoms were rated.';

    const payload = {
      riskLevel: localAssessment.level,
      concernType: localAssessment.concernType,
      symptomSummary,
      redFlags: localAssessment.redFlags,
      recommendations: localAssessment.recommendations,
    };

    try {
      const res = await fetch(`${API_BASE_URL}/v1/intake/final-report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errorText = await res.text();
        console.error('Final report API error:', res.status, errorText);

        setRiskAssessment(localAssessment);
        setStep(4);
        return;
      }

      const data = (await res.json()) as {
        riskLevel: 'Low' | 'Moderate' | 'High';
        concernType: string;
        summary: string;
        analysis: string;
        recommendations: string[];
        disclaimer: string;
        safetyNotes: string[];
      };

      const merged: RiskAssessment = {
        level: localAssessment.level,
        concernType: localAssessment.concernType,
        brief: data.summary || localAssessment.brief,
        redFlags: localAssessment.redFlags,
        analysis: data.analysis || localAssessment.analysis,
        recommendations: data.recommendations?.length
          ? data.recommendations
          : localAssessment.recommendations,
      };

      setRiskAssessment(merged);

      ///Call generate-questions endpoint, LLM suggests follow-up questions
      if (clinicalSummary) {
        try {
          const qRes = await fetch(
            `${API_BASE_URL}/v1/intake/generate-questions`,
            {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                concernType: selectedConcern,
                clinicalSummary,
              }),
            }
          );

          if (qRes.ok) {
            const qData = (await qRes.json()) as {
              concernType: string;
              questions: string[];
              rationaleNotes?: string[];
              safetyNotes?: string[];
            };

            if (Array.isArray(qData.questions)) {
              setDoctorQuestions(qData.questions);
            }
          } else {
            console.error(
              'Questions API error:',
              qRes.status,
              await qRes.text()
            );
          }
        } catch (err) {
          console.error('Network error (generate-questions):', err);
        }
      } else {
        setDoctorQuestions([]);
      }

      setStep(4);
    } catch (err) {
      console.error('Network error (final-report):', err);
      setRiskAssessment(localAssessment);
      setStep(4);
    } finally {
      setIsLoading(false);
    }
  };

  /////////////////////////////
  //Reset handler for the flow
  //Clears all state so the user (or tester) can run another intake.
  ////////////////////////////
  const handleReset = () => {
    setStep(1);
    setFreeText('');
    setConcernSuggestions([]);
    setSelectedConcern('');
    setSymptomRatings([]);
    setRiskAssessment(null);
    setClinicalSummary(null);
    setDoctorQuestions([]);
  };

  ///////////////////////
  ///Render: 4-step guided intake with progress header
  ///////////////////////
  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      style={styles.container}
      keyboardVerticalOffset={Platform.OS === 'ios' ? 90 : 0}
    >
      <ThemedView style={styles.container}>
        <ThemedView style={[styles.header, { paddingTop: insets.top + 12 }]}>
          <ThemedText type="title" style={styles.headerTitle}>
            Health Consultation
          </ThemedText>
          <ThemedText type="default" style={styles.headerSubtitle}>
            Step {step} of {TOTAL_STEPS}
          </ThemedText>

          {/*Progress Visual stepper 4-step flow*/}
          <View style={styles.progressContainer}>
            {Array.from({ length: TOTAL_STEPS }).map((_, i) => (
              <View key={i} style={styles.progressWrapper}>
                <View
                  style={[
                    styles.progressDot,
                    i < step && styles.progressDotActive,
                  ]}
                />
                {i < TOTAL_STEPS - 1 && (
                  <View
                    style={[
                      styles.progressLine,
                      i < step - 1 && styles.progressLineActive,
                    ]}
                  />
                )}
              </View>
            ))}
          </View>
        </ThemedView>

        <ScrollView
          style={styles.content}
          contentContainerStyle={[
            styles.scrollContent,
            { paddingBottom: insets.bottom + 20 },
          ]}
          showsVerticalScrollIndicator={false}
        >
          {/*STEP1: FREE TEXT INPUT*/}
          {step === 1 && (
            <View style={styles.stepContainer}>
              <ThemedText type="subtitle" style={styles.stepTitle}>
                What brings you in today?
              </ThemedText>
              <ThemedText type="default" style={styles.stepDescription}>
                Describe your main concern or symptoms in your own words.
              </ThemedText>

              <TextInput
                style={styles.textInput}
                value={freeText}
                onChangeText={setFreeText}
                placeholder="e.g., I've been having chest pain and feeling short of breath..."
                placeholderTextColor="#9CA3AF"
                multiline
                numberOfLines={6}
              />

              <Pressable
                style={[
                  styles.primaryButton,
                  !freeText.trim() && styles.buttonDisabled,
                ]}
                onPress={handleAnalyzeText}
                disabled={!freeText.trim() || isLoading}
              >
                {isLoading ? (
                  <ActivityIndicator color="#FFFFFF" />
                ) : (
                  <ThemedText style={styles.buttonText}>
                    Analyze Symptoms
                  </ThemedText>
                )}
              </Pressable>
            </View>
          )}

          {/*STEP2: CONCERN SELECTION*/}
          {step === 2 && (
            <View style={styles.stepContainer}>
              <ThemedText type="subtitle" style={styles.stepTitle}>
                Select the concern that best matches
              </ThemedText>
              <ThemedText type="default" style={styles.stepDescription}>
                Based on your description, here are possible concerns:
              </ThemedText>

              <View style={styles.concernList}>
                {concernSuggestions.map((concern, index) => (
                  <Pressable
                    key={index}
                    style={styles.concernCard}
                    onPress={() => handleSelectConcern(concern)}
                  >
                    <View style={styles.concernIcon}>
                      <ThemedText style={styles.concernEmoji}>🩺</ThemedText>
                    </View>
                    <View style={styles.concernContent}>
                      <ThemedText type="defaultSemiBold">
                        {concern}
                      </ThemedText>
                      <ThemedText style={styles.concernArrow}>→</ThemedText>
                    </View>
                  </Pressable>
                ))}
              </View>

              <Pressable style={styles.linkButton} onPress={() => setStep(1)}>
                <ThemedText style={styles.linkText}>
                  ← Go back and edit description
                </ThemedText>
              </Pressable>
            </View>
          )}

          {/*STEP 3: SYMPTOM SLIDERS*/}
          {step === 3 && (
            <View style={styles.stepContainer}>
              <ThemedText type="subtitle" style={styles.stepTitle}>
                {selectedConcern}
              </ThemedText>
              <ThemedText type="default" style={styles.stepDescription}>
                Rate the severity of each symptom you're experiencing:
              </ThemedText>

              <View style={styles.slidersList}>
                {symptomRatings.map((rating, index) => (
                  <View key={index} style={styles.sliderItem}>
                    <View style={styles.sliderHeader}>
                      <ThemedText
                        type="defaultSemiBold"
                        style={styles.sliderLabel}
                      >
                        {rating.symptom}
                      </ThemedText>
                      <View
                        style={[
                          styles.severityBadge,
                          rating.severity === 0 && styles.severityNone,
                          rating.severity === 1 && styles.severityMild,
                          rating.severity === 2 && styles.severityModerate,
                          rating.severity === 3 && styles.severitySevere,
                        ]}
                      >
                        <ThemedText style={styles.severityBadgeText}>
                          {SEVERITY_LABELS[rating.severity]}
                        </ThemedText>
                      </View>
                    </View>

                    <Slider
                      style={styles.slider}
                      minimumValue={0}
                      maximumValue={3}
                      step={1}
                      value={rating.severity}
                      onValueChange={(value) =>
                        handleUpdateSeverity(index, value)
                      }
                      minimumTrackTintColor="#3B82F6"
                      maximumTrackTintColor="#E5E7EB"
                      thumbTintColor="#3B82F6"
                    />
                  </View>
                ))}
              </View>

              <Pressable
                style={styles.primaryButton}
                onPress={handleGenerateAssessment}
                disabled={isLoading}
              >
                {isLoading ? (
                  <ActivityIndicator color="#FFFFFF" />
                ) : (
                  <ThemedText style={styles.buttonText}>
                    Generate Assessment
                  </ThemedText>
                )}
              </Pressable>

              <Pressable style={styles.linkButton} onPress={() => setStep(2)}>
                <ThemedText style={styles.linkText}>
                  ← Change concern
                </ThemedText>
              </Pressable>
            </View>
          )}

          {/*STEP 4: RISK ASSESSMENT & RECOMMENDATIONS*/}
          {step === 4 && riskAssessment && (
            <View style={styles.stepContainer}>
              <ThemedText type="subtitle" style={styles.stepTitle}>
                Your Health Assessment
              </ThemedText>

              <View
                style={[
                  styles.riskBanner,
                  riskAssessment.level === 'Low' && styles.riskLow,
                  riskAssessment.level === 'Moderate' && styles.riskModerate,
                  riskAssessment.level === 'High' && styles.riskHigh,
                ]}
              >
                <ThemedText type="subtitle" style={styles.riskLevel}>
                  Risk Level: {riskAssessment.level}
                </ThemedText>
                <ThemedText style={styles.riskConcern}>
                  {riskAssessment.concernType}
                </ThemedText>
              </View>

              {/*Brief summary of intake*/}
              <View style={styles.summarySection}>
                <ThemedText
                  type="defaultSemiBold"
                  style={styles.sectionTitle}
                >
                   Summary
                </ThemedText>
                <ThemedText style={styles.summaryText}>
                  {riskAssessment.brief}
                </ThemedText>
              </View>

              {/*Detailed Analysis*/}
              <View style={styles.summarySection}>
                <ThemedText
                  type="defaultSemiBold"
                  style={styles.sectionTitle}
                >
                   Analysis
                </ThemedText>
                <ThemedText style={styles.summaryText}>
                  {riskAssessment.analysis}
                </ThemedText>
              </View>

              {/*Next steps with clinician*/}
              <View style={styles.summarySection}>
                <ThemedText
                  type="defaultSemiBold"
                  style={styles.sectionTitle}
                >
                   Recommendations
                </ThemedText>
                {riskAssessment.recommendations.map((rec, index) => (
                  <View key={index} style={styles.listItem}>
                    <ThemedText style={styles.bullet}>•</ThemedText>
                    <ThemedText style={styles.summaryText}>{rec}</ThemedText>
                  </View>
                ))}
              </View>

              {/*Generated Questions for Clinician*/}
              {doctorQuestions.length > 0 && (
                <View style={styles.summarySection}>
                  <ThemedText
                    type="defaultSemiBold"
                    style={styles.sectionTitle}
                  >
                     Questions to ask your clinician
                  </ThemedText>
                  {doctorQuestions.map((q, index) => (
                    <View key={index} style={styles.listItem}>
                      <ThemedText style={styles.bullet}>•</ThemedText>
                      <ThemedText style={styles.summaryText}>{q}</ThemedText>
                    </View>
                  ))}
                </View>
              )}

              {/*Safety disclaimer highlighting prototype*/}
              <View style={styles.disclaimer}>
                <ThemedText style={styles.disclaimerText}>
                  ⚕️ This assessment is for informational purposes only and
                  does not replace professional medical advice. Always consult a
                  healthcare provider for proper diagnosis and treatment.
                </ThemedText>
              </View>

              {/*Future/prototype actions (currently non-functional)*/}
              <View style={styles.actionButtons}>
                <Pressable style={styles.secondaryButton}>
                  <ThemedText style={styles.secondaryButtonText}>
                    Find Clinics
                  </ThemedText>
                </Pressable>
                <Pressable style={styles.secondaryButton}>
                  <ThemedText style={styles.secondaryButtonText}>
                    Save Report
                  </ThemedText>
                </Pressable>
              </View>

              {/*Allows the user to rerun the flow from the beginning*/}
              <Pressable style={styles.primaryButton} onPress={handleReset}>
                <ThemedText style={styles.buttonText}>
                  Start New Consultation
                </ThemedText>
              </Pressable>
            </View>
          )}
        </ScrollView>
      </ThemedView>
    </KeyboardAvoidingView>
  );
}


/////////////////////////////////////////////////////
////TypeScript Styles Below - Designed the Webapp////
/////////////////////////////////////////////////////

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTitle: {
    fontFamily: Fonts.rounded,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 13,
    opacity: 0.6,
    marginBottom: 16,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#D1D5DB',
  },
  progressDotActive: {
    backgroundColor: '#3B82F6',
  },
  progressLine: {
    width: 40,
    height: 2,
    backgroundColor: '#D1D5DB',
    marginHorizontal: 4,
  },
  progressLineActive: {
    backgroundColor: '#3B82F6',
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
  },
  stepContainer: {
    gap: 16,
  },
  stepTitle: {
    fontSize: 20,
  },
  stepDescription: {
    opacity: 0.7,
    lineHeight: 20,
  },
  textInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    fontSize: 15,
    minHeight: 120,
    textAlignVertical: 'top',
    color: '#1F2937',
  },
  primaryButton: {
    backgroundColor: '#3B82F6',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  buttonDisabled: {
    backgroundColor: '#D1D5DB',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  concernList: {
    gap: 12,
  },
  concernCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  concernIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#EFF6FF',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  concernEmoji: {
    fontSize: 24,
  },
  concernContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  concernArrow: {
    fontSize: 20,
    color: '#3B82F6',
  },
  linkButton: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  linkText: {
    color: '#3B82F6',
    fontSize: 14,
  },
  slidersList: {
    gap: 20,
  },
  sliderItem: {
    gap: 8,
  },
  sliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sliderLabel: {
    fontSize: 15,
  },
  severityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  severityNone: {
    backgroundColor: '#F3F4F6',
  },
  severityMild: {
    backgroundColor: '#FEF3C7',
  },
  severityModerate: {
    backgroundColor: '#FED7AA',
  },
  severitySevere: {
    backgroundColor: '#FEE2E2',
  },
  severityBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  slider: {
    width: '100%',
    height: 40,
  },
  riskBanner: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
  },
  riskLow: {
    backgroundColor: '#ECFDF5',
    borderColor: '#10B981',
  },
  riskModerate: {
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
  },
  riskHigh: {
    backgroundColor: '#FEE2E2',
    borderColor: '#EF4444',
  },
  riskLevel: {
    fontSize: 18,
    marginBottom: 4,
  },
  riskConcern: {
    fontSize: 14,
    opacity: 0.8,
  },
  redFlagSection: {
    padding: 16,
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 15,
    marginBottom: 8,
  },
  redFlagText: {
    fontSize: 14,
    color: '#DC2626',
    flex: 1,
    lineHeight: 20,
  },
  summarySection: {
    padding: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
  },
  summaryText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#4B5563',
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bullet: {
    fontSize: 14,
    marginRight: 8,
    color: '#4B5563',
  },
  disclaimer: {
    padding: 16,
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
  },
  disclaimerText: {
    fontSize: 13,
    lineHeight: 18,
    color: '#92400E',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  secondaryButtonText: {
    color: '#4B5563',
    fontSize: 15,
    fontWeight: '600',
  },
});
